// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Index',
    },
    {
      type: 'category',
      label: 'CRM Core',
      items: ['01-crm-core'],
    },
    {
      type: 'category',
      label: 'Offers, Invoices, Fiscalization',
      items: ['02-offers-invoicing-fiscalization'],
    },
    {
      type: 'category',
      label: 'AI Assistant',
      items: ['03-ai-assistant'],
    },
    {
      type: 'category',
      label: 'Call Center',
      items: ['04-call-center'],
    },
    {
      type: 'category',
      label: 'Marketing Module',
      items: ['05-marketing-integrations-and-attribution'],
    },
    {
      type: 'category',
      label: 'Roles, Team collab.',
      items: ['06-multi-role-team-collaboration'],
    },
    {
      type: 'category',
      label: 'Billing, Access, Roles',
      items: ['07-billing-account-access-roles'],
    },
    {
      type: 'category',
      label: 'Security',
      items: ['08-devops-security-audit'],
    },
    {
      type: 'category',
      label: 'Scheduling & Calendar',
      items: ['09-scheduling-calendar'],
    },
    {
      type: 'category',
      label: 'User Onboarding',
      items: ['10-user-onboarding-and-guidance'],
    },
  ],
};

export default sidebars;
